server:
  port: 8084
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/neo
    username: neo_test
    password: neo@Test123
    hikari:
      auto-commit: true
      idle-timeout: 180000
      pool-name: sequence.server-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 10
